### ISSUE TITLE
Invalid comparison of rrd version

### ISSUE THREAD

**Issue by branislavgligorov** [munin-monitoring/munin#1284] opened 2020-02-26 08:38 UTC
Munin version 2.0.30. plugin for WHM (cPanel) in file:
/usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Munin/Master/GraphOld.pm
on line 545 there is:

push @$result, '--slope-mode' if $RRDs::VERSION >= 1.2;

but $RRDs::VERSION comes as "1.5.5." which can not be changed to number in order to be evaluated against "1.2" so in log file munin-graph.log there is: 

[PERL WARNING] Argument "1.5.5" isn't numeric in numeric ge (>=) at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Munin/Master/GraphOld.pm line 545

Quick fix is to change line 545 to: 

push @$result, '--slope-mode' if (substr $RRDs::VERSION, 0, 3) >= 1.2;

Of course this is just quick fix in my case and this line should be improved in next version.

**Comment by sumpfralle** [comment] 2020-02-29 01:06
Thank you for your report!

Indeed this comparison fails with a non-numeric content of `$RRDs::VERSION`.

Interestingly this version comparison was first introduced in 2005 (508811ed854082b361981e127d0f8428f47adcc8) and I am not aware of bug reports against it up to now (but maybe the old bug tracker contains one). Currently the comparison works, since at least RRD v1.7.2 reports as `1.70021`, thus allowing numeric comparison. It is quite confusing, that the comparison seems to have worked in the past (when the comparison was introduced) and that it works now.

Even the source history of rrdtool contains only numeric version descriptions down to very old versions (e.g. `$VERSION=1.2026;`).

Thus I am confused: what is the source of the RRDs perl package, that you use?

**Comment by branislavgligorov** [comment] 2020-03-06 08:18
yum info cpanel-rrdtool.x86_64
gives:
Name        : cpanel-rrdtool
Arch        : x86_64
Version     : 1.5.5
Release     : 1.cp1158
Size        : 3.3 M
Repo        : installed
Summary     : A helper tool used when compiling applications and libraries
URL         : http://rrdtool.freedesktop.org/wiki/
License     : GPLv2
Description : RRDtool

**Comment by sumpfralle** [comment] 2020-03-06 18:55
Interesting!

Could you please share your file `RRDs.pm` (probably belonging to this package or its perl bindings) with us?

**Comment by branislavgligorov** [comment] 2020-03-06 20:54
Here it is, I just added extension ".txt" to be able to upload here.
[RRDs.pm.txt](https://github.com/munin-monitoring/munin/files/4300355/RRDs.pm.txt)

**Comment by sumpfralle** [comment] 2020-03-07 05:34
Thanks for your source of `RRDs`.

I compared the file to the `RRDs.pm` file contained in the upstream repository (https://github.com/oetiker/rrdtool-1.x). It seems that the `cpanel` maintainers (?) or your hosting provider decided to use a modified version of that file. At least the change from [commit 711f9caa3d](https://github.com/oetiker/rrdtool-1.x/commit/711f9caa3dffe6d2348d7d69d41e92d983b04086) is missing from your file, even though it is part of the upstream repository since v.1.5.0.

Very weird.

From my point of view the source of the problem is the non-upstream version of `RRDs.pm` on your system. I am not really convinced, that we (munin) should work around such exotic environments.

@steveschnepp: do you have an opinion?

**Comment by branislavgligorov** [comment] 2020-03-07 22:40
Yes it is weird. It VPS with plain CentOS7 and regular WHM/cPanel setup and I just do regular updates without any special settings - I did not change any file by myself.
Maybe it will be sorted up in next WHM/cPanel update?

**Comment by sumpfralle** [comment] 2020-03-08 06:22
> Maybe it will be sorted up in next WHM/cPanel update?

I assume, that you increase the probability of this event by filing a bug report there. Hopefully :)

**Comment by sumpfralle** [comment] 2020-03-19 21:36
@branislavgligorov: please add a link here, after you filed a bug report against your hosting provider. This will help other users stumbling upon the same issue.

**Comment by sumpfralle** [comment] 2021-02-21 22:02
Closing, since it seems to be a problem caused by modifications of the hosting provider.

**Closed by sumpfralle** 2021-02-21 22:02 UTC
Labels: [affects] 2.0-stable, [affects] branch master
