### ISSUE TITLE
Cannot view stats when server is down.

### ISSUE THREAD

**Issue by colinmollenhour** [munin-monitoring/munin#706] opened 2016-05-03 22:10 UTC
Here is an example of a server that has been down for about 30 minutes. I'd like to see the stats right before the server went down to see if there could be a load issue, but I cannot view the stats at all: http://screencast.com/t/YnCb0sd3

**Comment by ssm** [comment] 2016-07-28 10:06
This depends on #720

**Comment by sumpfralle** [comment] 2018-06-26 02:42
Duplicate of #579

**Closed by sumpfralle** 2018-06-26 02:42 UTC
Labels: [affects] 2.0-stable, [affects] branch master, [component] master, [type] bug
