### ISSUE TITLE
exim_mailstats: File rotated, starting at start

### ISSUE THREAD

**Issue by doublehp** [munin-monitoring/munin#924] opened 2018-03-06 21:57 UTC
munin-node.log

```
2018/03/06-06:25:34 [20795] Error output from exim_mailstats:
2018/03/06-06:25:34 [20795]     exim_mailstats: File rotated, starting at start
```

Same as bug #923 ... plugin should catch the issue, and handle it properly without letting any error message going out.

**Comment by sumpfralle** [comment] 2018-03-06 23:13
`exim_mailstats` is just one of many consumers of the related `tail_open` function.
Thus this is a duplicate of #923.

**Closed by sumpfralle** 2018-03-06 23:13 UTC
