### ISSUE TITLE
[apt_all] on 2.0.72 update cron fails on bookworm

### ISSUE THREAD

**Issue by JulienPalard** [munin-monitoring/munin#1521] opened 2023-03-08 17:01 UTC
**Describe the bug**

On Debian bookworm, I'm getting:

```
E: The value 'bookworm-backports' is invalid for APT::Default-Release as such a release is not available in the sources
E: The value 'bookworm-security' is invalid for APT::Default-Release as such a release is not available in the sources
E: The value 'bookworm-updates' is invalid for APT::Default-Release as such a release is not available in the sources
```

**To Reproduce**
1. Install munin-plugins-core on Debian bookworm
2. run `/usr/share/munin/plugins/apt_all update 7200 1`
3. See error

**Desktop (please complete the following information):**
 - OS+Distribution Version: Debian Bookworm
 - Munin Version 2.0.72

**Additional context**

It happens when apt_all runs:

    apt-get "-o" "Debug::pkgDepCache::AutoInstall=false" "-o" "APT::Get::Show-Versions=false" "-u" "dist-upgrade" "--print-uris" "--yes" "-t" "bookworm-backports"

the `bookworm-backports` may come from the `guess_releases` function.

The `guess_releases` function already trim `/updates`, maybe it should trim `-updates`, `-backports`, and `-security`? Or maybe there's a better way to obtain the list of releases?

**Comment by JulienPalard** [comment] 2023-03-08 17:14
The relevant code from apt around this error:

```
   if (DefRel.empty() == false)
   {
      bool found = false;
      for (pkgCache::PkgFileIterator F = Cache->FileBegin(); F != Cache->FileEnd(); ++F)
      {
         if (pkgVersionMatch::ExpressionMatches(DefRel, F.Archive()) ||
             pkgVersionMatch::ExpressionMatches(DefRel, F.Codename()) ||
             pkgVersionMatch::ExpressionMatches(DefRel, F.Version()) ||
             (DefRel.length() > 2 && DefRel[1] == '='))
            found = true;
      }
      // "now" is our internal archive name for the status file,
      // which we should accept even if we have no status file at the moment
      if (not found && pkgVersionMatch::ExpressionMatches(DefRel, "now"))
         found = true;
      if (not found)
         _error->Error(_("The value '%s' is invalid for APT::Default-Release as such a release is not available in the sources"), DefRel.c_str());
      else
         CreatePin(pkgVersionMatch::Release,"",DefRel,990);
   }

```

**Comment by matcatc** [comment] 2023-06-20 02:13
I am also getting the error with bookworm-updates, although I am not getting the error with bookworm-security:

```
E: The value 'bookworm-updates' is invalid for APT::Default-Release as such a release is not available in the sources
```

I am able to reproduce this error by executing the `apt-get` command directly on the command line. Interestingly, this command works just fine with bullseye-updates (on a separate computer that is running Bullseye.)

Note that the following two links both indicate that bookworm-updates is valid:

* https://wiki.debian.org/DebianBookworm
* https://wiki.debian.org/SourcesList

I suspect this is an issue with Debian, but searching the mailing list and online I am unable to find anything. (This issue was the closest thing I found, personally.)

> The `guess_releases` function already trim `/updates`, maybe it should trim `-updates`, `-backports`, and `-security`? Or maybe there's a better way to obtain the list of releases?

Using apt_all plugin on Bullseye, I've noticed that all the release, release-backports, etc. can have a different number of available packages and are plotted as separate lines in the generated graphs. So trimming the end would in effect be removing several lines from the generated graphs. Personally, I'd like if the lines for these were kept.

**Comment by ruliane** [comment] 2023-06-23 14:29
Releases can be defined in your _/etc/munin/plugin-conf.d/apt_all_:
```
[apt_all]
user root
env.releases bookworm bookworm-security
```

However, to ensure this file is read upon cronjob, the job must be rewrite to use munin-run instead of the plugin directly. You can change your cronjob from:
`*/5 * * * *    root if [ -x /etc/munin/plugins/apt_all ]; then /etc/munin/plugins/apt_all update 7200 12 >/dev/null; elif [ -x /etc/munin/plugins/apt ]; then /etc/munin/plugins/apt update 7200 12 >/dev/null; fi`
to
`*/5 * * * *    root if [ -x /etc/munin/plugins/apt_all ]; then /usr/sbin/munin-run apt_all update 7200 12 >/dev/null; elif [ -x /etc/munin/plugins/apt ]; then /usr/sbin/munin-run apt update 7200 12 >/dev/null; fi`

By using munin-run, plugins are run with the `munin` user. That's why I also specified `user root` in the plugin-conf.d.

**Comment by ruliane** [comment] 2023-06-23 14:43
Here are some additional considerations:

- Anyway, it is a good practice to start plugins with `munin-run` instead of executing them directly.


- > The `guess_releases` function already trim `/updates`, maybe it should trim `-updates`, `-backports`, and `-security`? Or maybe there's a better way to obtain the list of releases?

AFAIK, these parts should not be removed. You **do** want to check for pending packages on the `-security` repo. ;)


- I have faced issues with this plugin and the cronjob for several Debian releases. And on every upgrade I secretly hope this to be fixed.

- I don't really know why _bookworm-updates_ is not a valid repo name. It actually [exists](http://ftp.debian.org/debian/dists/bookworm-updates/).

**Comment by thbemme** [comment] 2023-07-01 13:25
The issue only appears during the cronjob that updates the repos:

```
/etc/munin/plugins/apt_all update 1 1
Hit:1 http://ftp2.de.debian.org/debian bookworm InRelease
Get:2 http://ftp2.de.debian.org/debian bookworm-updates InRelease [52.1 kB]
Hit:3 http://security.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
E: The value 'bookworm-updates' is invalid for APT::Default-Release as such a release is not available in the sources
```

The munin-run part doesn't produce the error:

```
sudo -u munin munin-run apt_all
pending_bookworm.value 0
hold_bookworm.value 0
pending_bookworm_security.value 0
hold_bookworm_security.value 0
```

**Comment by ruliane** [comment] 2023-07-01 13:38
Yes, this is because the standard munin-run part only reads a file located in `/var/lib/munin-node/plugin-state/` and prints it to stdout.
The error appears during the update process, when the plugin runs `apt-get update` to update the content of this file.

**Comment by ruliane** [comment] 2023-07-01 13:40
Since it looks like a Debian-specific bugs, I think we should file a bug at https://bugs.debian.org/ and suggest the changes I mentioned in comment https://github.com/munin-monitoring/munin/issues/1521#issuecomment-1604366526.

**Comment by matcatc** [comment] 2023-07-09 23:06
> Releases can be defined in your _/etc/munin/plugin-conf.d/apt_all_

My 2c: I considered doing this in my setup, but decided against it since I didn't want to have to worry about keeping my sources.list and the munin configuration in sync (e.g.: when upgrading to a new release.)

> Since it looks like a Debian-specific bugs, I think we should file a bug at https://bugs.debian.org/

I considered doing this. From reading through the Debian documentation, bugs are reported against packages. In this case, we might be able to report against apt or a related package. Or perhaps against Debian's munin package. The documentation also suggests reaching out to the Debian user mailing list for advice if unsure which package to report a bug against.

**Comment by agx** [comment] 2023-07-10 18:20
The package would be [munin-plugins-core](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=munin-plugins-core;dist=unstable) as the issue affects the plugin. I don't think `apt` does anything wrong here.

That said the bug is not *specific* to Debian, it affects the `apt_all` shipped in munin upstream (so people e.g. installing from source are affected the same). So having it filed in Debian is fine but fixing it upstream would also be good (and it would tickle into Debian that way).

**Comment by agx** [comment] 2023-07-10 18:29
> I don't really know why bookworm-updates is not a valid repo name. It actually [exists](http://ftp.debian.org/debian/dists/bookworm-updates/).

```
# "apt-get" "-o" "Debug::pkgDepCache::AutoInstall=false" "-o" "APT::Get::Show-Versions=false" "-u" "dist-upgrade" "--print-uris" "--yes" "-t"  bookworm-updates
Reading package lists... Done
E: The value 'bookworm-updates' is invalid for APT::Default-Release as such a release is not available in the sources
```

I think this is because `bookworm-updates` doesn't contain any packages yet. It will likely go away with the first point release so this might be an issue for apt after all (fails on empty suites).

**Comment by sokai** [comment] 2024-10-11 13:42
FYI: for me (in the meantime) this problem is gone … KR

**Comment by steveschnepp** [comment] 2024-10-11 13:54
Thanks! Let's close it and reopen it eventually for the next Debian release 😉

**Closed by steveschnepp** 2024-10-11 13:54 UTC

**Comment by agx** [comment] 2024-10-11 15:47
It's not fixed though. Debian just made a point release in the mean time.

**Comment by steveschnepp** [comment] 2024-10-11 17:37
I know.
