### ISSUE TITLE
host not shown on html pages per categories for subgraphs

### ISSUE THREAD

**Issue by doublehp** [munin-monitoring/munin#787] opened 2017-01-19 11:43 UTC
For example: I clicking in the main web page, in the left column, on label "direct_map"
/munin/direct_map-day.html
seems a subgraph for multigraph memory or meminfo (not sure which one). But the text title above image is not giving the source host:
":: mmap "

while other plugins usually provide it; example in the Sensor section:
"leon-01.doublehp.org :: Temperatures "

I know the bug is about multigraph; but I don't know which kind of multigraph (plugin providing several main graphs, or, if it's only about subgraphs). Hard to track for me because all subgraphs from official trunk plugins are broken on all my machines.

The bug is located in the script that generates the html pages, for the section called "Categories" (3rd part of left column).

Munin version 2.0.28-1

**Comment by sumpfralle** [comment] 2018-02-19 02:06
I noticed the symptom you described (missing hostname in front of the graph title) now with the following plugins:
* `ath9k_` (from contrib):
    * "Station Events" (all failed)
    * "Station Traffic" (some worked, some failed)
    * "Station Transmit Rates" (all failed)
* olsrd (from contrib):
    * "link_quality" (some worked, some failed)
    * "neighbour_link" (some worked, some failed)
* diskstats_ (core):
    * "latency" (all failed)
    * "throughput" (all failed)
    * "utilization" (all failed)
    * "iops" (all failed)

Maybe it helps to analyze the cause of this issue ...

**Comment by shallot** [comment] 2019-09-07 23:18
Just confirming that meminfo is definitely doing this badly

**Comment by sumpfralle** [comment] 2020-03-23 02:49
Finally this issue is fixed in b2b7a8cef4c8c9504c55cb0d181dc4b56af00437.

**Closed by sumpfralle** 2020-03-23 02:49 UTC
Labels: [affects] 2.0-stable, [component] web cgi, [type] bug
