### ISSUE TITLE
Problems not showing anything

### ISSUE THREAD

**Issue by kewubenduben** [munin-monitoring/munin#778] opened 2017-01-13 18:39 UTC
Even though the there's a critical problem and it's sending me email notifications, the web interface doesn't show the problem.

Screenshot at http://prntscr.com/dv90eu

**Comment by golgoth777** [comment] 2017-01-14 09:51
Hi, could you make sure your munin-node plugin configuration (/etc/munin/plugin-conf.d/munin-node in my centos) has env.warning and env.critical defined ?

/etc/munin/plugin-conf.d/munin-node :
```
[df*]
env.exclude none unknown iso9660 squashfs udf romfs ramfs debugfs
env.warning 92
env.critical 98
```

**Comment by thecantero** [comment] 2017-01-14 18:24
@golgoth777, Hi. Yes. The thing is, I do get the email alerts when warning and critical are encountered.

My problem is that the WebUI `problems` list isn't showing anything at all.

**Comment by sumpfralle** [comment] 2018-03-20 01:06
duplicate of #457

**Closed by sumpfralle** 2018-03-20 01:06 UTC
Labels: [affects] branch master, [component] web interface, [type] question, duplicate
