### ISSUE TITLE
trivial typo in plugin netstat

### ISSUE THREAD

**Issue by doublehp** [munin-monitoring/munin#930] opened 2018-03-12 16:28 UTC
> 2018/03/12 16:11:44 [WARNING] Service netstat onXXXXXX:4949 returned no data for label active

After some digging:

host1:
```
# netstat -s | grep active
    13238 active connections openings
```

host2:
```
# netstat -s | grep active
    19646 active connection openings
```

see the 's' at the end of word connection ?

I don't how to fix awk, but just find a rule making s optionnal; my fix will be dirty:

```
netstat -s | awk '
/active connections ope/  { print "active.value " $1 }
/active connection ope/  { print "active.value " $1 }
/passive connection ope/  { print "passive.value " $1 }
/failed connection/       { print "failed.value " $1 }
/connection resets/       { print "resets.value " $1 }
/connections established/ { print "established.value " $1 }'
```

You would prefer something like
`/active connection[s]* ope/  { print "active.value " $1 }`
but I am not sure this is valid in awk

**Comment by doublehp** [comment] 2018-03-12 20:16
Here is an explanation from Debian upgrade changelogs:

> net-tools (1.60+git20161116.90da8a0-1) unstable; urgency=medium
> 
>   After 15 years without upstream development, net-tools is being worked on
>   again, fixing many long-standing issues.
> 
>   The bad news is that the output of many commands has changed, and it is sure
>   to break scripts that relied on parsing it.
> 
>   If you have customs scripts that use any of these commands, please make sure
>   they still work after this upgrade:
> 
>     netstat, ifconfig, ipmaddr, iptunnel, mii-tool, nameif, plipconfig, rarp,
>     route, slattach, arp.
> 
>   Apologies in advance for the trouble that this may cause, but maintaining a
>   separate version of net-tools just to keep the old format is something I am
>   not able to do.
> 
>  -- MartÃ­n Ferrari <tincho@debian.org>  Mon, 26 Dec 2016 05:29:25 +0000

**Comment by sumpfralle** [comment] 2018-03-12 20:45
Thank you for digging through the issue!
Indeed the problem was reported before and will be fixed with the next Debian package upgrade, if nothing goes wrong.

Closing as duplicate of #877.

Thank you!

**Closed by sumpfralle** 2018-03-12 20:45 UTC
