### ISSUE TITLE
One Minute update interval not working, configure plugin with update_rate 60 leads to NAN in Reports

### ISSUE THREAD

**Issue by markusweb** [munin-monitoring/munin#1304] opened 2020-03-19 13:31 UTC
**Describe the bug**
we nee to have a more detailed Monitoring. so as a first test i wanted to have the cpu Plugin with a one Minute upate. i added

update_rate 60
graph_data_size custom 1d, 1m for 1d, 1m for 1w, 5m for 1t, 15m for 1y

into the config-section of the cpu Plugin script, i deleted all the rrd-files for cpu

after running munin-cron the rrds files are generated but when i Dump them i only get NaN as value. the graph also Shows NaN

i have reaed https://github.com/munin-monitoring/munin/issues/711#issue-161095364 but even with first adding update_rate and then removing it i will not get any data.

**Desktop (please complete the following information):**
 - OS+Distribution Version SuSE SLES 12.SP4
 - Munin Version 2.0.56

is there any good documentation About one Minute update interval? 
i have read https://software.danielwatrous.com/increase-munin-resolution-to-one-minute/ but a few Questions are not answered. 

as far as i understood running munin-cron in 5 minutes should be enough and it should collect the data from the nodes and Plugins even if the Plugins defines different update_rates. is this correct? 

i collect the data via munin-asyncd so the update interval for the Graphs (munin-cron) should not matter on the master, Right?

there is no munin-node cron Job as munin-node is a process running in Background. should it check every 60s the Plugin state if i use update_rate 60?

**Comment by sumpfralle** [comment] 2020-03-19 18:25
> after running munin-cron the rrds files are generated but when i Dump them i only get NaN as value. the graph also Shows NaN

I tried to reproduce this here. After a few minutes, the rrd file started to contain values:
```
rrdinfo /var/lib/munin/localdomain/localhost.localdomain-load-load-g.rrd|grep value
ds[42].value = 1.5390000000e+01
rra[0].cdp_prep[0].value = NaN
rra[1].cdp_prep[0].value = NaN
rra[2].cdp_prep[0].value = NaN
rra[3].cdp_prep[0].value = NaN
rra[4].cdp_prep[0].value = NaN
rra[5].cdp_prep[0].value = NaN
rra[6].cdp_prep[0].value = NaN
rra[7].cdp_prep[0].value = NaN
rra[8].cdp_prep[0].value = NaN
rra[9].cdp_prep[0].value = 0.0000000000e+00
rra[10].cdp_prep[0].value = inf
rra[11].cdp_prep[0].value = -inf
rra[12].cdp_prep[0].value = 2.5000000000e-01
rra[13].cdp_prep[0].value = 2.5000000000e-01
rra[14].cdp_prep[0].value = 2.5000000000e-01
```

Do you have an idea, what is different on your host?

> as far as i understood running munin-cron in 5 minutes should be enough and it should collect the data from the nodes and Plugins even if the Plugins defines different update_rates. is this correct?

This works, but it only collects the values in intervals of 5 minutes.

> i collect the data via munin-asyncd so the update interval for the Graphs (munin-cron) should not matter on the master, Right?

Collecting the values with smaller time intervals via `munin-asyncd` is the proper approach. This will spool the data and allow the master to retrieve all values.

> there is no munin-node cron Job as munin-node is a process running in Background. should it check every 60s the Plugin state if i use update_rate 60?

`munin-node` does nothing on its own - it is just waiting for requests. The service should be queried regularly by either the master or the `munin-asyncd` process.

**Comment by markusweb** [comment] 2020-03-20 13:34
ah, now it works.

i made two cron jubs. just one with munin-update running every minute. and one to generate the Graphs running every 5 minutes.

i use munin-async. there is a minrate switch, Default to 300. so if munin-node just waits to be triggered i have to Change the update rate in munin-async to 60. 

thanxs

**Comment by markusweb** [comment] 2020-04-06 09:14
I did not see how to configure different update rates for plugins. is it possible to mix say the default 5 minaute and 1 minute rate with different plugins?
when i switched to the 1 minute rate i only see graphs for plugins with 1 minute update rate. the other plugins with default 5 minute rate are not generated (i have not checked whether the data is generated).

markus

**Comment by sumpfralle** [comment] 2020-04-06 12:53
> I did not see how to configure different update rates for plugins. is it possible to mix say the default 5 minaute and 1 minute rate with different plugins?

Using the wanted `update_rate` statement in each plugin's configuration should be sufficient, I guess.

> when i switched to the 1 minute rate i only see graphs for plugins with 1 minute update rate. the other plugins with default 5 minute rate are not generated (i have not checked whether the data is generated).

Please check, where the problem occurs:
* is the spool area of `munin-asyncd` populated and regularly updated (as configured for each plugin)?
* are the rrd files updated on the master (every five minutes)?
* do you see errors in any of munin's log files?

**Comment by sumpfralle** [comment] 2021-02-21 21:58
I assume, the problem is fixed?

**Comment by shallot** [comment] 2021-08-02 16:22
These symptoms sound like the same thing as #1409 actually

**Comment by sumpfralle** [comment] 2021-08-08 14:22
> These symptoms sound like the same thing as #1409 actually

Yes, that sounds reasonable. Thus I am closing this issue. Please report back, if there is something left ...

**Closed by sumpfralle** 2021-08-08 14:22 UTC
