### ISSUE TITLE
df plugin ignores order of mounts, emits notifications for reordering

### ISSUE THREAD

**Issue by azrdev** [munin-monitoring/munin#351] opened 2015-02-26 13:42 UTC
I'm running munin-node 2.0.25 on Fedora 21. I've configured `contacts` in munin master to email me.
Until recently, **I got a lot of emails** from the `df` and `df_inode` plugins, always **with `OKs` lines, no `ERRORs`**. The mount points in these mails never changed, only their order. This was mostly occuring when someone logged in or out (via ssh, the machine is headless).
I figured the plugins call `df`, which reads `/etc/mtab`, which is not guaranteed to be in any specific order. And it treats a changed order like mountpoints were changed, and re-issues a notification.
Thus I (think I) could **fix this by including  `| sort`** into the shell call issued by the plugin. Maybe another solution would be to store the mountpoints in a set - but I don't know enough perl, to see if that's a good approach.

**Comment by gnuheidix** [comment] 2015-09-01 15:57
I had the same problem on a machine which mounted a `tmpfs` for each logged in user. e.g.:
```
tmpfs                44232        0     44232        0% /run/user/1000
```

I fixed the problem by adding the following configuration to the munin-node because I personally don't care about these mountpoints.
```
[df]
env.exclude_re ^/run/user
```

**Comment by ssm** [comment] 2015-09-02 20:41
As far as I know, /run, and everything below it, would be a tmpfs, so it should possibly be ignored by a number of plugins monitoring disk activity

**Comment by gnuheidix** [comment] 2015-09-04 11:03
Actually, I wouldn't want to have all `tmpfs` mounts to be ignored. Some are quite useful to have monitoring enabled on.

e.g. the Varnish shmlog
``` 
tmpfs            64M   18M   47M  27% /var/lib/varnish
```

**Comment by ssm** [comment] 2015-09-13 11:13
This is a duplicate of #561, which is closed.  I'll close this as well.

**Closed by ssm** 2015-09-13 11:13 UTC
Labels: duplicate, [affects] version 2.x, [component] plugins, [type] bug
