### ISSUE TITLE
CDEF: fields cannot reference other fields

### ISSUE THREAD

**Issue by shapirus** [munin-monitoring/munin#664] opened 2016-01-30 15:59 UTC
The way CDEFs are now implemented makes it impossible to reference other fields in them.

Consider the following (real) situtation. I need to put TokuDB database engine's cache usage on a graph. The relevant data source variables are:

```
limit: total size of cache memory
cloned: used for smth
rollback: used for smth
leaf: used for smth
nonleaf: used for smth
```

Naturally I'd like to display this similarly to the CPU graph: some light color for the unused memory, everything else stacked below and probably on top of the unused memory (like CPU's iowait goes on top of idle).

The problem here is that the "limit" field represents total memory amount rather than free memory. Therefore to get the free memory amount, it is needed to subtract all the used memory from it. It would be easy with a CDEF like

```
limit.cdef limit,cloned,rollback,leaf,nonleaf,+,+,+,-
```

The problem is that munin-graph doesn't parse the other fields in this definition and leaves them as is, but during the field processing loop they are expanded to avg, min and max values and their original names are lost. In the end, rrdtool receives the following options:

```
CDEF:min_limit=min_r_limit,cloned,rollback,leaf,nonleaf,+,+,+,- 
CDEF:avg_limit=avg_r_limit,cloned,rollback,leaf,nonleaf,+,+,+,-
CDEF:max_limit=max_r_limit,cloned,rollback,leaf,nonleaf,+,+,+,-
```

and fails because of unknown field names.

I ended up putting limit on the graph first, draw type AREA, then the first "used" field next with type AREA again, and then the rest of the fields after it with type AREASTACK. This way the limit area stays in the background with only the free memory visible above the used one. It isn't very nice because the free memory color can only be at the top.

**Comment by shapirus** [comment] 2016-01-30 21:17
also see #522

**Comment by sumpfralle** [comment] 2021-01-30 15:50
I am just diving a bit into Munin's cdef processing (e.g. see #1379).

I do not fully understand the above issue description:
1. is the translation from `limit` to `min_r_limit` a problem? (the naming surprises me a bit, but Munin's translation should work in general)
2. are you sure, that field names like `cloned` are not translated? I am quite confident, that they are turned into `acloned` (and other prefixed names) correctly.

But maybe this is a fruitless endeavour, since the issue is a bit old by now ...

**Comment by shapirus** [comment] 2021-01-30 18:22
I would gladly elaborate, but unfortunately I haven't been using Munin for about 5 years now, pretty much since the time I created this issue. I fail to remember any details of this today. Too bad I didn't provide more details (or a pull request!) while I was a good bit familiar with the Munin source code back then.

It sounds like I was suggesting that the processed definition should have looked like this:

```
CDEF:min_limit=min_r_limit,min_r_cloned,min_r_rollback,min_r_leaf,min_r_nonleaf,+,+,+,- 
CDEF:avg_limit=avg_r_limit,avg_r_cloned,avg_r_rollback,avg_r_leaf,avg_r_nonleaf,+,+,+,-
CDEF:max_limit=max_r_limit,max_r_cloned,max_r_rollback,max_r_leaf,max_r_nonleaf,+,+,+,-
```

or maybe not exactly that, but the idea is that rrdtool has to be able to compute the value from all the specified fields and arithmetic operations.

The easiest way to understand this would be to try to reproduce a similar setup while looking at the Munin code at the same time.

**Comment by sumpfralle** [comment] 2021-02-21 20:35
After taking a look at #766, I think, this issue is related (references to fields which are not known, yet).

Thus I guess, we can close this issue due to being a duplicate. Please re-open, if you disagree.

**Closed by sumpfralle** 2021-02-21 20:35 UTC
Labels: [affects] branch master, [component] master, [type] bug

**Comment by shapirus** [comment] 2021-02-22 07:54
All right, I will check if it works if I ever have to configure it again (if #766 is closed by that time). Hope I will :).
