### ISSUE TITLE
munin-update: UNIQUE constraint failed error, and node list not updating in sqlite after adding lots of nodes

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#422] opened 2015-04-07 14:03 UTC
Munin-update ends with:

```
DBD::SQLite::st execute failed: UNIQUE constraint failed: url.path at /srv/munin/sandbox/lib/perl5/Munin/Master/Update.pm line 525.
DBD::SQLite::st execute failed: UNIQUE constraint failed: url.path at /srv/munin/sandbox/lib/perl5/Munin/Master/Update.pm line 525.
```

RRD files are updated, but none of the new nodes are visible in munin-httpd. All of the old ones are.

All the node FQNs and addresses are unique in the configuration files. All the hostname banners on the munin nodes are unique.

The line referenced in the perl module is:

```
$sth_url->execute($ds_id, "ds", _get_url_from_path("$host:$_service:$data_source"));
```

**Comment by steveschnepp** [comment] 2015-04-07 16:00
That's very interesting, since it means that the corresponding generated url is the same. Which should not happen if the corresponding service has a distinct url.

**Comment by leeclemens** [comment] 2015-06-07 16:06
I am seeing the same error and behavior with a new master installation of 2.1.12, but connecting to an existing node (2.0). `ds` table has 0 rows.

```
DBD::SQLite::st execute failed: UNIQUE constraint failed: url.path at /munininstallbase/lib/perl5/Munin/Master/Update.pm line 533.
DBD::SQLite::st execute failed: UNIQUE constraint failed: url.path at /munininstallbase/lib/perl5/Munin/Master/Update.pm line 533.
```

- mtime on the rrd's and .storable are updated for the single node
- sqlite database is copied to a new version with the pid appended to it
- original database with no rows in table `ds` remains unmodified

Running munin-cron twice results in two datafile.sqlite.`<pid>` files of the same size:
```
-rw-r--r--. 1 munin munin  27648 Jun  7 09:59 datafile.sqlite
-rw-r--r--. 1 munin munin 267264 Jun  7 10:13 datafile.sqlite.26453
-rw-r--r--. 1 munin munin 267264 Jun  7 10:17 datafile.sqlite.31006
```

I added some debugging to see what it is being duplicated, but nothing is created in logdir (exists, writable by munin user) and logs seem to be going to syslog (and subsequently rate-limited, dropping my debugging statements).

**Comment by leeclemens** [comment] 2015-06-07 16:31
I removed only the `proc` plugin and was able to execute `munin-update` successfully.

**Comment by steveschnepp** [comment] 2019-06-17 05:35
I cannot reproduce this bug with 2.999.12, even when adding 1k plugins at once.

Therefore closing it. Please reopen if there's a way to reproduce.

**Closed by steveschnepp** 2019-06-17 05:35 UTC
Labels: [affects] branch master, [component] master
