### ISSUE TITLE
Bug in HTMLOld.pm on ArchLinux

### ISSUE THREAD

**Issue by IlikePepsi** [munin-monitoring/munin#519] opened 2015-07-23 15:27 UTC
I'm encountering a bug when the munin-cgi-html script is executed by apache, when a user requests data. I'm on an ArchLinux machine and therefore made related post in the ArchLinux forum. Please help.

https://bbs.archlinux.org/viewtopic.php?id=200127

**Comment by sumpfralle** [comment] 2018-03-02 23:32
Is this still an issue?

**Comment by sumpfralle** [comment] 2018-06-26 02:15
Maybe the problem is based on the Arch packaging?
Closing for now due to lack information ...

**Closed by sumpfralle** 2018-06-26 02:15 UTC
Labels: [affects] 2.0-stable, [component] master, [todo] needs more information, [type] bug
