### ISSUE TITLE
[feature] add plugin for tor

### ISSUE THREAD

**Issue by ilf** [munin-monitoring/munin#1314] opened 2020-04-14 17:01 UTC
Since 2014, there's a plugin to monitor stats about Tor: https://github.com/daftaupe/munin-tor

Could this be added to [the existing plugins](https://github.com/munin-monitoring/munin/tree/master/plugins)?

Would be great to have this in [Debian munin-plugins-extra](https://packages.debian.org/unstable/munin-plugins-extra).

Thanks!

**Comment by sumpfralle** [comment] 2020-04-15 14:28
This plugin as already part of the `contrib` repository: https://github.com/munin-monitoring/contrib/blob/master/plugins/tor/tor_ (more recently updated than the version you linked above).

It can easily be retrieved via `munin-get install contrib/tor_` (`munin-get` is available since munin 2.0.52).

> Would be great to have this in Debian munin-plugins-extra.

Indeed. At the moment the Debian packages use only plugins from munin's core repository. But we try to keep the amount of plugins directly shipped with munin small in order to ease maintenance.  We (the Debian package maintainer) did not yet decide, how to handle the possible packaging of plugins from the `contrib` repository. Feel free to encourage such a discussion on munin's IRC channel (`#munin` at irc.oftc.net).

Thus for now I close this issue, since the plugin is already maintained in the munin project.

**Closed by sumpfralle** 2020-04-15 14:28 UTC

**Comment by ilf** [comment] 2020-04-15 16:15
> (`munin-get` is available since munin 2.0.52).

Thanks. But Debian stable only has [2.0.49](https://packages.debian.org/stable/munin) :)

**Comment by h01ger** [comment] 2020-04-15 16:27
On Wed, Apr 15, 2020 at 09:15:52AM -0700, ilf wrote:
> > (`munin-get` is available since munin 2.0.52).
> Thanks. But Debian stable only has [2.0.49](https://packages.debian.org/stable/munin) :)

stable-bpo has 2.0.56


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by ilf** [comment] 2020-04-15 16:42
> stable-bpo has 2.0.56

Thanks, but unfortunately Raspbian [doesn't have backports](http://raspbian.raspberrypi.org/raspbian/dists/).
