### ISSUE TITLE
lighttpd2 rewrite rule

### ISSUE THREAD

**Issue by debiansid** [munin-monitoring/munin#875] opened 2017-09-17 14:12 UTC
I am trying to make munin 2.0.33 working on my lighttpd2 instance.(which was working on my lighttpd 1.4.35)
I got almost everything working including cgi part. now the only thing not working is rewrite part.

here is doc about lighttpd2 rewrite.
https://doc.lighttpd.net/lighttpd2/mod_rewrite.html#mod_rewrite

I am not sure it will work on lighttpd2 ,but highly appreciate to any help.

munin.conf for lightpd2
```
munin = {

        alias  [ "/munin-static/" => "/etc/munin/static",
                 "/munin/"        => "/var/cache/munin/www/",
               ];

        rewrite  (
                   "/favicon.ico" => "/var/cache/munin/www/static/favicon.ico",
                   "/static/(.*)" => " /var/cache/munin/www/static/$1",
                   "/munin/(.*)" => "/munin-cgi/munin-cgi-html/$1",
                   "/munin-cgi/munin-cgi-html$" => "/munin-cgi/munin-cgi-html/",
                   "/munin-cgi/munin-cgi-html/static/(.*)" => "/munin-static/$1"
                );
        if req.path =^ "/munin-cgi/munin-cgi-html/" {
        fastcgi "unix:/var/run/lighttpd/munin-cgi-html.sock";
        if req.path =^ "/munin-cgi/munin-cgi-graph/" {
        fastcgi "unix:/var/run/lighttpd/munin-cgi-graph.sock";
    }
}
};
```

access.log

```
l Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:29 +0800] "GET /munin/static/logo-h.png HTTP/1.1" 304 5874 "http://nas.home:8080/munin/static/style-new.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:30 +0800] "GET /munin/ HTTP/1.1" 200 11436 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:30 +0800] "GET /munin/static/style-new.css HTTP/1.1" 304 11592 "http://nas.home:8080/munin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:30 +0800] "GET /munin/static/logo-h.png HTTP/1.1" 304 11748 "http://nas.home:8080/munin/static/style-new.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:32 +0800] "GET /munin/home/index.html HTTP/1.1" 200 17310 "http://nas.home:8080/munin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:32 +0800] "GET /munin/home/static/style-new.css HTTP/1.1" 404 18243 "http://nas.home:8080/munin/home/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:32 +0800] "GET /munin/home/static/favicon.ico HTTP/1.1" 404 19176 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"
192.168.88.11 nas.home - [17/Sep/2017:22:06:32 +0800] "GET /munin/home/static/favicon.ico HTTP/1.1" 404 20109 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0"


```

**Comment by sumpfralle** [comment] 2017-09-17 20:11
Did you already took a look at the [lighttpd example](http://guide.munin-monitoring.org/en/latest/example/webserver/lighttpd.html) in den munin guide?
It uses munin-httpd instead of cgi.

If you want to stick to your cgi approach: which redirect/rewrite operations do not work as expected for you?

**Comment by debiansid** [comment] 2017-09-18 00:54
Rewrite rule only works for /munin , any other page does not. 
check the access_log , those 404 items , show rewrite is not right.

**Comment by debiansid** [comment] 2017-09-18 00:59
click the link in page, it will become 
`solaris10.strangled.net:8022/munin/home/gw.home/home/gw.home/home/home/gw.home/home/gw.home/home/gw.home/home/nas.home/home/nas.home/home/index.html`

**Comment by debiansid** [comment] 2017-09-18 01:22
![fail](https://github.com/debiansid/shadowsocks-libev-archlinux/raw/master/images/71F06FFF-E5A8-4EC0-8061-BFBC96CE47F3.png)

**Comment by sumpfralle** [comment] 2017-09-18 02:43
> click the link in page, it will become

I did not find the link you referred to.
Please share a specific request with us (e.g. provide a curl commandline example), if your munin server is public. Otherwise it is hard for others to help you diagnose your problem.

I would suggest to comment out line by line of your configuration until you find the problematic configuration directive that causes the recursive redirects.

**Comment by debiansid** [comment] 2017-09-19 15:19
@sumpfralle
I made an demo here ![demo](http://204.152.220.66/munin/)

**Comment by sumpfralle** [comment] 2017-09-19 23:26
It is a bit hard to study an unknown blackbox from the outside :(

I noticed the following:
* the links to `static/style-new.css` do not depend on the current page level (e.g. it should be `../../static/style-new.css` [here](http://204.152.220.66/munin/localdomain/localhost.localdomain/index.html))
* the [host overview](http://204.152.220.66/munin/localdomain/localhost.localdomain/index.html) is empty - did you collect any data? (see `munin-update.log`)

Maybe you want to setup the munin web-interface based on apache (which is well-known - and probably pre-configured in your distribution). Then you compare each rendered page with your lighttpd setup and analyze the cause of the existing differences.

**Comment by debiansid** [comment] 2017-09-19 23:35
@sumpfralle 
you can check here [demo on port 8080](http://204.152.220.66:8080/munin/), this is on lighttpd 1.4. same munin backend. you will understand my question.

**Comment by sumpfralle** [comment] 2017-09-20 00:34
I am sorry - you have lost me completely :(

Is this a lighttpd question?
It feels like your problem is related to munin only by accident.

Or maybe I misunderstand you?

**Comment by debiansid** [comment] 2017-09-20 00:54
I have 2 Lighttpd versions installed. the one listen port 80 which is lighttpd 2.0; the 8080 one is lighttpd1.4, they are serving the same munin backend. Rewrite rule in 1.4 is from [here](http://guide.munin-monitoring.org/en/stable-2.0/example/webserver/lighttpd.html), lighttpd2.0 has different rewrite grammar which is where I need help.

**Comment by sumpfralle** [comment] 2017-09-20 01:00
OK - I understand.

I am afraid, that you will not find a lot of detailed lighttpd knowledge here in the munin project (it would be just by accident).

Please report back your config as soon as you managed to get it working. It would certainly deserve a place in munin's documentation.

**Comment by sumpfralle** [comment] 2018-02-17 21:51
Any news on this?

Otherwise I would tend to close this issue, since it is out of scope for the munin repository.

**Closed** 2018-02-17 23:12 UTC
