### ISSUE TITLE
Dynazoom: dates replaced with "NaN" on Safari / Mac OS

### ISSUE THREAD

**Issue by stephane-isvtec** [munin-monitoring/munin#874] opened 2017-09-12 12:16 UTC
On Safari / Mac OS when updating the dates values (either start_iso8601, stop_iso8601, start_epoch or stop_epoch) in dynazoom and validating using the "update" button, dates are replaced with "NaN" values.

Url example:
- before: https://xxx.xxx/munin/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=Default/HOSTNAME/load&size_x=800&size_y=400&start_epoch=1505094760&stop_epoch=1505202760
- after update: https://xxx.xxx/munin/static/dynazoom.html?plugin_name=Default%2FHOSTNAME%2Fload&start_iso8601=2017-09-11T05%3A52%3A40%2B0400&stop_iso8601=2017-09-12T11%3A52%3A40%2B0400&start_epoch=NaN&stop_epoch=NaN&lower_limit=&upper_limit=&size_x=800&size_y=400&cgiurl_graph=%2Fmunin-cgi%2Fmunin-cgi-graph

![screen shot 2017-09-12 at 16 15 39](https://user-images.githubusercontent.com/22585734/30325408-abcc8c72-97d5-11e7-96d5-6833d2bd4dbe.png)

**Comment by GoodBoy962** [comment] 2017-09-23 16:19
Could you give a plan how to install munin on Mac?

**Comment by dipohl** [comment] 2017-09-23 17:29
On Sat, 23 Sep 2017 16:19:51 +0000 (UTC)
Pliskin Alexander wrote:

> Could you give a plan how to install munin on Mac?
> 

Which version of Munin do you want to install?

There exists a (very old) tutorial in Trac wiki:
http://munin-monitoring.org/wiki/MuninInstallationDarwin

Concerning the webserver configuration
you can find some examples in the Munin Guide:
http://guide.munin-monitoring.org/en/latest/example/index.html

HTH,

Gabriele

**Comment by GoodBoy962** [comment] 2017-09-24 19:40
@dipohl I wont install it on mac os. I used this manual for that https://codingnightly.wordpress.com/2013/10/27/monitor-macosx-using-munin/. But when I open the url in the browser there is just only a link to the parent folder. And there is nothing in /opt/local/www/munin folder

**Comment by dipohl** [comment] 2017-09-24 20:23
On Sun, 24 Sep 2017 19:40:04 +0000 (UTC)
Pliskin Alexander wrote:

> I used this manual for that https://codingnightly.wordpress.com/2013/10/27/monitor-macosx-using-munin/. 

This tutorial was written in 2013 and refers to an outdated Munin version

Quote: "Tested on OSX 10.9, Xcode 5, MacPorts 2.2.1, Munin 1.4.7"

Recent Munin Version is 2.0.33

Which version of Munin did you install?

**Comment by GoodBoy962** [comment] 2017-09-24 21:14
@dipohl 
I used port to install it. The version it tries to install is 1.4.7. It doesn't matter for me which version to install. Could you please provide the manual for installing any version and configuring it. 
It will be grate to have something like https://www.digitalocean.com/community/tutorials/how-to-install-the-munin-monitoring-tool-on-ubuntu-14-04

**Comment by dipohl** [comment] 2017-09-24 21:39
On Sun, 24 Sep 2017 21:14:26 +0000 (UTC)
Pliskin Alexander wrote:

> Could you please provide the manual for installing any version and configuring it. 
> It will be grate to have something like https://www.digitalocean.com/community/tutorials/how-to-install-the-munin-monitoring-tool-on-ubuntu-14-04

http://guide.munin-monitoring.org/en/latest/tutorial/getting-started.html

**Comment by stephane-isvtec** [comment] 2017-09-25 04:30
Seems I forgot to add important information regarding this issue.

Munin is installed on a Debian Jessie server. Munin version is:
```
ii  munin                                 2.0.25-1+deb8u3                  all          network-wide graphing framework (grapher/gatherer)
ii  munin-common                          2.0.33-1~bpo8+1                  all          network-wide graphing framework (common)
ii  munin-node                            2.0.25-1+deb8u3                  all          network-wide graphing framework (node)
ii  munin-plugins-core                    2.0.25-1+deb8u3                  all          network-wide graphing framework (plugins for node)
ii  munin-plugins-cyb                     1.0-19                           all          Munin plugins used locally by cyb
ii  munin-plugins-extra                   2.0.25-1+deb8u3                  all          network-wide graphing framework (user contributed plugins for node)
```

Safari on Mac OS is only for accessing the web interface. The problems does not occur on Firefox or Chrome so we believe it may be related to a Javascript incompatibility.

**Comment by sumpfralle** [comment] 2018-02-17 22:03
@stephane-isvtec: thank you for providing the version numbers.

The version mix of 2.0.25 and 2.0.33 is a bit confusing for me. I think, you installed munin-common from the backports repository, but sticked to stable with the other packages. Maybe you want to switch the other packages to the ones from backports, too?

Regarding the issue:
* it concerns only one browser
* the current munin master branch deviated quite a lot from the previous web templates from 2.x
* thus a fix for this issue would only be relevant for the old 2.x series

Personally, I doubt, that someone will take to the time to tackle this issue :(
(just thinking aloud)

**Comment by cyril-bouthors** [comment] 2018-11-16 18:45
A fixture to reproduce this bug is available here, thanks to @stephane-isvtec:

https://paste.isvtec.com/munin/

**Comment by sumpfralle** [comment] 2018-11-17 00:32
The development console of my browser shows some `Content Security Policy` errors while loading this page. Is this part of the problem?

**Comment by stephane-isvtec** [comment] 2019-01-24 06:45
No (I don't have this error when loading the page using Safari 12).

To see the problem, load the page and click on the "update" button. The Start & Stop fields get updated with "NaN-NaN-NaNTNaN:NaN:NaN-NaNNaN"

**Comment by cycloon** [comment] 2019-10-28 15:10
I just ran into this problem and analysed it a bit:

1. The problem comes from a javascript function not using new Date() in a portable way
2. The problem seems still to exist in current master branch (see [web/static/js/munin-dynazoom.js](https://github.com/munin-monitoring/munin/blob/7a231ebebff0c05c6dbcf240aa507e71c06bb2e3/web/static/js/munin-dynazoom.js#L238) )

problematic code from function majDates(event):
`		var date_parsed = new Date(stop_manual.replace(dateRegex, "$2 $3, $1 $4:$5:$6"));`

this code basically resolves to something like this:
`		var date_parsed = new Date("10 28, 2019 15:15:05");`

that is: "day, month year time".

According to the the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) this is not ideal at least. This version of the constructor is not available in all implementations. Also there is a warning not to use the constructor to parse date strings. The same seems to be true for `Date.parse()`.

The section of code should be either reworked to create a Date from an ISO Timestamp or using individual Date parts as in:
`		var date_parsed = new Date(2019, 10, 28, 15, 15, 05);`

**Comment by cycloon** [comment] 2019-10-28 16:02
I just created a pull request #1245 to fix this problem.

**Comment by sumpfralle** [comment] 2019-10-29 03:02
@cycloon: thank you for analyzing the issue and contributing a fix. It is merged now.

**Closed by sumpfralle** 2019-10-29 03:02 UTC
Labels: [affects] 2.0-stable, [component] web interface
