### ISSUE TITLE
Muni snmp problem

### ISSUE THREAD

**Issue by Owned67** [munin-monitoring/munin#893] opened 2017-11-16 01:09 UTC
Hello,

`munin-node -v`

> Version:
>     This is munin-node v2.0.33-1

 `cat /etc/os-release`

> NAME="Ubuntu"
> VERSION="17.04 (Zesty Zapus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 17.04"
> VERSION_ID="17.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=zesty
> UBUNTU_CODENAME=zesty

in /etc/munin/plugin-conf.d/munin-node file:
`[snmp*]
env.community public

cd /etc/munin/plugins
ln -s /usr/share/munin/plugins/snmp__if_ /etc/munin/plugins/snmp_192.168.1.15_if_2
ln -s /usr/share/munin/plugins/snmp__if_err_ /etc/munin/plugins/snmp_192.168.1.15_if_err_2`

restart munin-node
```
$ munin-run snmp_192.168.1.15_if_2 --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
 # Setting /rgid/ruid/ to /121/65534/
 # Setting /egid/euid/ to /121 121/65534/
 # Setting up environment
 # Environment community = public
 # About to run '/etc/munin/plugins/snmp_192.168.1.15_if_2'
 recv.value U
 send.value U
```

http://localhost/168.1.15/192.168.1.15/snmp_192_168_1_15_if_2.html return no graph with:

This graph shows traffic for the "0x436f6e6e6578696f6e2061752072e973656175206c6f63616c2a203132" network interface.

How to fix please "0x436f6e6e6578696f6e2061752072e973656175206c6f63616c2a203132" ?

Service SNMP is installed on my windows 10.

On my server ubuntu:
snmpwalk -c public -v 2c 192.168.1.15 return http://termbin.com/ftdt

Thanks

**Comment by niclan** [comment] 2017-11-16 10:55
On 16. nov. 2017 02:09, Owned67 wrote:
> Environment community = public
> About to run '/etc/munin/plugins/snmp_192.168.1.15_if_2'
>
> recv.value U
> send.value U

That is the first problem, no graph because you are not getting any 
readings.

> This graph shows traffic for the 
> "0x436f6e6e6578696f6e2061752072e973656175206c6f63616c2a203132" network 
> interface.

I wonder if the SNMP-agent returns a string in a quoted form that the 
library we're using is not decoding for us.

Do you have any perl skils? Or a willingness to try to figure out 
something you understand poorly?

Nicolai

**Comment by Owned67** [comment] 2017-11-16 11:33
Do you have any perl skils? => No

Or a willingness to try to figure out
something you understand poorly? => understand what? I'l use a transaltor for speak english...... ^^

**Comment by niclan** [comment] 2017-11-16 13:27
@Owned67: To fix this one would need access to the munin install to debug the plugin. (or to reproduce it, but I have no windows).

If you could upload the snmp__if_ plugin here, then I'll edit it some to help reveal the problem and possibly solve it.

**Comment by Owned67** [comment] 2017-11-16 14:09
I have access (ssh, ftp).

Upload? it's if_ plugin from official munin...

Link: http://termbin.com/i4ke

**Comment by Owned67** [comment] 2017-11-16 15:21
@niclan sorry, i have mistake file, i have edited and now it's snmp_if, very sorry...

**Comment by sumpfralle** [comment] 2018-02-17 17:03
> snmpwalk -c public -v 2c 192.168.1.15 return http://termbin.com/ftdt

Was this a relevant piece of information for debugging this issue?
Could you please share it with us again? (it delivers 404 right now)

**Comment by niclan** [comment] 2018-02-19 22:13
I find myself unable to follow up this in any meaningful way with the snatches of time I have available.

**Comment by sumpfralle** [comment] 2018-03-28 18:58
@Owned67: would you like to comment on my [last question](https://github.com/munin-monitoring/munin/issues/893#issuecomment-366455181)?

**Comment by Owned67** [comment] 2018-03-29 12:10
your link is broken, he stay here :x

**Comment by sumpfralle** [comment] 2019-10-19 01:32
Closing for now due to a lack of information. Please re-open, if you still encounter this issue.

**Closed by sumpfralle** 2019-10-19 01:32 UTC
Labels: [affects] 2.0-stable, [todo] needs more information, [type] bug
