### ISSUE TITLE
2.999: Critical/warning/unknown status function doesn't work

### ISSUE THREAD

**Issue by laulicus** [munin-monitoring/munin#917] opened 2018-03-01 14:07 UTC
Munin master - commit id 84e3c1a5603c7c30229efed3bd8bed036471fffa

Munin doesn't show critical, warning and unknown status and doesn't draw yellow and red borders as in version 2.x

**Comment by sumpfralle** [comment] 2018-03-20 01:08
duplicate of #457

**Closed by sumpfralle** 2018-03-20 01:08 UTC
Labels: [affects] branch master, [component] web interface, duplicate
