### ISSUE TITLE
munin-asyncd does not extend global update_rate to plugin update rates

### ISSUE THREAD

**Issue by shallot** [munin-monitoring/munin#1409] opened 2021-07-12 14:13 UTC
When you reduce your munin master update rate from 300 to 60 seconds, munin-asyncd breaks, as it doesn't actually run the plugins at a rate of <300s, so the master keeps getting no data in spoolfetch

To reproduce, just provision munin master with update_rate 60 and watch munin-update log record numerous
"[INFO] No spoofetch data for ..." messages

BTW there's an obvious typo in that log message

https://github.com/munin-monitoring/munin/blob/master/script/munin-asyncd#L223 currently says:

			my $plugin_rate = $spoolwriter{$node}->get_metadata("plugin_rates/$plugin") || 300;

...should probably say || $update_rate ?

**Comment by sumpfralle** [comment] 2021-07-14 22:16
> BTW there's an obvious typo in that log message

fixed in ee6823846573e1278ca12d21d0e2b764fc7d7852, thanks!

> ...should probably say || $update_rate ?

Yes, I changed it to `$minrate` now (the value configurable during startup).

Does that fix the issue with the broken `munin-asyncd` for shorter periods? (I do not have an async setup at hand to try ...)

**Comment by shallot** [comment] 2021-07-19 10:21
I tested just replacing 300 with 60 in the meantime and that indeed made it work quite well

I'll change 60 to $minrate in my patch and test again, but it stands to reason that it'll work, because the same variable is already used within the same code flow a few lines above

**Comment by sumpfralle** [comment] 2021-07-19 11:24
That sounds good!

Thus I assume, that - given your ongoing test is successful - the issue you raised is solved now? Or do you see other problems?

**Comment by shallot** [comment] 2021-08-02 16:19
It looks good from this perspective, thanks

Happily switched over 4 different Munin installations to async ssh now :)

**Comment by sumpfralle** [comment] 2021-08-08 14:20
Thank you for reporting back - I am glad, the issue is fixed now!

**Closed by sumpfralle** 2021-08-08 14:20 UTC
